apiVersion: v1
kind: Secret
metadata:
  name: empresa-backend-secrets
  namespace: empresa
type: Opaque
stringData:
  DB_URL: "..."
  DB_USER: "..."
  DB_PASS: "..."
  TENANT_ID: "..."
  CLIENT_ID: "..."
  CLIENT_SECRET: "..."